name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/kings-kitchen:latest .

      - name: Push Image to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker push $DOCKERHUB_USERNAME/kings-kitchen:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull latest Docker image
        run: |
          docker pull roshan121923/kings-kitchen:latest

      - name: Stop old container
        run: |
          docker rm -f kings-kitchen || true

      - name: Run new container
        run: |
          docker run -d \
            --name kings-kitchen \
            -p 3000:3000 \
            roshan121923/kings-kitchen:latest

      - name: Check container
        run: |
          docker ps
