name: CI/CD Pipeline

on:
  push:
    branches:
      - muskan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: muskan-${{ github.sha }}
        run: |
          docker build -t $DOCKERHUB_USERNAME/kings-kitchen:$IMAGE_TAG .
          docker tag $DOCKERHUB_USERNAME/kings-kitchen:$IMAGE_TAG $DOCKERHUB_USERNAME/kings-kitchen:muskan

      - name: Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_TAG: muskan-${{ github.sha }}
        run: |
          docker push $DOCKERHUB_USERNAME/kings-kitchen:$IMAGE_TAG
          docker push $DOCKERHUB_USERNAME/kings-kitchen:muskan

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull Muskan Docker Image
        run: |
          docker pull roshan121923/kings-kitchen:muskan

      - name: Stop Old Muskan Container
        run: |
          docker rm -f kings-kitchen-muskan || true

      - name: Run Muskan Container
        run: |
          docker run -d \
            --name kings-kitchen-muskan \
            -p 3001:3000 \
            roshan121923/kings-kitchen:muskan

      - name: Check Container
        run: |
          docker ps

          